name: Compile JSON to SRS and Upload Release

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  compile-and-release:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install sing-box
        run: |
          sudo mkdir -p /etc/apt/keyrings
          sudo curl -fsSL https://sing-box.app/gpg.key -o /etc/apt/keyrings/sagernet.asc
          sudo chmod a+r /etc/apt/keyrings/sagernet.asc
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/sagernet.asc] https://deb.sagernet.org/ * *" | \
            sudo tee /etc/apt/sources.list.d/sagernet.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y sing-box

      - name: Clone SukkaLab Repository
        run: git clone --depth=1 https://github.com/SukkaLab/ruleset.skk.moe ruleset

      - name: Compile JSON to SRS
        run: |
          mkdir -p output
          find ruleset/sing-box -type f -name "*.json" | while read -r json_file; do
            dir_name=$(basename "$(dirname "$json_file")")
            file_name=$(basename "$json_file" .json)
            output_file="output/${dir_name}@${file_name}.srs"
            sing-box rule-set compile "$json_file" -o "$output_file"
          done

      - name: Set timestamp tag
        id: set_tag
        run: |
          TAG=$(date +'%Y%m%d%H%M%S')  # 格式化为年月日时分秒
          echo "TAG=${TAG}" >> $GITHUB_ENV

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: output/*.srs
          tag: ${{ env.TAG }}
          overwrite: true
          file_glob: true

      - name: Upload binaries to latest release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: output/*.srs
          tag: latest
          overwrite: true
          file_glob: true
