name: Compile JSON to SRS and Upload Release

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发
  workflow_dispatch:  # 支持手动触发工作流

jobs:
  compile-and-release:
    runs-on: ubuntu-latest

    steps:
      # 检出当前代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 安装 sing-box
      - name: Install sing-box
        run: |
          sudo mkdir -p /etc/apt/keyrings
          sudo curl -fsSL https://sing-box.app/gpg.key -o /etc/apt/keyrings/sagernet.asc
          sudo chmod a+r /etc/apt/keyrings/sagernet.asc
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/sagernet.asc] https://deb.sagernet.org/ * *" | \
            sudo tee /etc/apt/sources.list.d/sagernet.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y sing-box

      # 克隆目标存储库
      - name: Clone SukkaLab Repository
        run: git clone --depth=1 https://github.com/SukkaLab/ruleset.skk.moe ruleset

      # 编译 JSON 文件为 SRS 文件
      - name: Compile JSON to SRS
        run: |
          mkdir -p output
          find ruleset/sing-box -type f -name "*.json" | while read -r json_file; do
            dir_name=$(basename "$(dirname "$json_file")")
            file_name=$(basename "$json_file" .json)
            output_file="output/${dir_name}@${file_name}.srs"
            sing-box rule-set compile "$json_file" -o "$output_file"
          done

      # 创建 Release（如果没有现成 Release）
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: latest
          release_name: SRS Files Release
          draft: false
          prerelease: false

      # 上传每个 SRS 文件到 Release
      - name: Upload SRS Files to Release
        run: |
          for file in output/*.srs; do
            gh release upload latest "$file" --clobber
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
